#!/bin/bash
# Script for building MotorsportRSS for Windows
# Author: AI Assistant
# Date: 2025-03-15

echo "MotorsportRSS Windows Build Script"
echo "=================================="
echo ""
echo "This script provides instructions for building MotorsportRSS for Windows."
echo "There are two approaches: Cross-compilation from Linux or direct build on Windows."
echo ""

echo "Option 1: Cross-compilation from Linux using MXE"
echo "-----------------------------------------------"
echo "1. Install MXE dependencies:"
echo "   sudo apt-get install -y autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev libssl-dev libtool-bin libxml-parser-perl lzip make openssl p7zip-full patch perl python3 python3-mako ruby sed unzip wget xz-utils"
echo ""
echo "2. Clone MXE repository:"
echo "   git clone --depth=1 https://github.com/mxe/mxe.git"
echo ""
echo "3. Build required Qt components (this will take several hours):"
echo "   cd mxe"
echo "   make MXE_TARGETS=x86_64-w64-mingw32.shared MXE_PLUGIN_DIRS=plugins/gcc10 qtbase qtsvg qtdeclarative qttools qtnetwork qtxml"
echo ""
echo "4. Add MXE binaries to your PATH:"
echo "   export PATH=/path/to/mxe/usr/bin:$PATH"
echo ""
echo "5. Build MotorsportRSS for Windows:"
echo "   cd /path/to/MotorsportRSS"
echo "   x86_64-w64-mingw32.shared-qmake-qt5"
echo "   make"
echo ""
echo "6. Collect dependencies:"
echo "   mkdir -p windows-build/MotorsportRSS"
echo "   cp release/MotorsportRSS.exe windows-build/MotorsportRSS/"
echo "   cp /path/to/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Core.dll windows-build/MotorsportRSS/"
echo "   cp /path/to/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Gui.dll windows-build/MotorsportRSS/"
echo "   cp /path/to/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Widgets.dll windows-build/MotorsportRSS/"
echo "   cp /path/to/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Svg.dll windows-build/MotorsportRSS/"
echo "   cp /path/to/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Network.dll windows-build/MotorsportRSS/"
echo "   cp /path/to/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Xml.dll windows-build/MotorsportRSS/"
echo "   mkdir -p windows-build/MotorsportRSS/platforms"
echo "   cp /path/to/mxe/usr/x86_64-w64-mingw32.shared/qt5/plugins/platforms/qwindows.dll windows-build/MotorsportRSS/platforms/"
echo "   mkdir -p windows-build/MotorsportRSS/resources"
echo "   cp -r resources/* windows-build/MotorsportRSS/resources/"
echo ""
echo "7. Create zip archive:"
echo "   cd windows-build"
echo "   zip -r MotorsportRSS-Windows.zip MotorsportRSS"
echo ""

echo "Option 2: Building directly on Windows"
echo "-------------------------------------"
echo "1. Install Qt for Windows (https://www.qt.io/download-qt-installer)"
echo "   - Install Qt 5.15.2 or newer with MinGW"
echo ""
echo "2. Clone the repository:"
echo "   git clone https://github.com/curdlinrope/Motorsport-RSS-Reader.git"
echo ""
echo "3. Open Qt Creator and open the MotorsportRSS.pro file"
echo ""
echo "4. Configure the project for MinGW"
echo ""
echo "5. Build the project (Ctrl+B)"
echo ""
echo "6. Deploy using windeployqt:"
echo "   cd build-MotorsportRSS-Desktop_Qt_5_15_2_MinGW_64_bit-Release/release"
echo "   C:/Qt/5.15.2/mingw81_64/bin/windeployqt.exe MotorsportRSS.exe"
echo ""
echo "7. Collect all files in the release directory into a zip file for distribution"
echo ""

echo "========================="
echo "Note: For either option, make sure the resources are properly bundled with the application."
echo "The final Windows build will be in a zip file containing the executable and all dependencies." 